# Generated by Django 3.0 on 2019-12-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
