# Generated by Django 3.0 on 2019-12-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_order_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
